### ISSUE TITLE
Script does not work with Subiquity installer or ISO images that include it

### ISSUE THREAD

**Issue by desrod** [covertsh/ubuntu-autoinstall-generator#14]
As titled, this script relies on the legacy d-i installer, which was deprecated in 20.04 and later releases, in favor of the new installer, Subiquity, which does not use the same files, configuration options nor constructs as the legacy installers. 

```
./ubuntu-autoinstall-generator.sh -k -a -u user-data -s ubuntu-21.04-live-server-amd64.iso 
[2021-07-05 20:51:24] 👶 Starting up...
[2021-07-05 20:51:24] 📁 Created temporary working directory /tmp/tmp.qRWehwZ9WJ
[2021-07-05 20:51:24] 🔎 Checking for required utilities...
[2021-07-05 20:51:24] 👍 All required utilities are installed.
[2021-07-05 20:51:24] ☑️ Using existing ubuntu-21.04-live-server-amd64.iso file.
[2021-07-05 20:51:24] 🤞 Skipping verification of source ISO.
[2021-07-05 20:51:24] 🔧 Extracting ISO image...
[2021-07-05 20:51:25] 👍 Extracted to /tmp/tmp.qRWehwZ9WJ
[2021-07-05 20:51:25] 🧩 Adding autoinstall parameter to kernel command line...
sed: can't read /tmp/tmp.qRWehwZ9WJ/isolinux/txt.cfg: No such file or directory
[2021-07-05 20:51:25] 🚽 Deleted temporary working directory /tmp/tmp.qRWehwZ9WJ
```

I was hoping to find an all-in-one that would produce a remastered ISO to auto-install 20.04 and later, but this doesn't yet work with those releases. I'll keep searching!

**Comment by covertsh** [comment]
Hi, thank you for opening an issue. The problem you are experiencing is real - this script does not yet work for Ubuntu 21.04. However, your comments are not correct. This **works correctly** for Ubuntu 20.04 (in fact, that is all it has been tested on). There is no reliance whatsoever on the legacy ```d-i``` installer.

I have a separate repository [here](https://github.com/covertsh/ubuntu-preseed-iso-generator) which does use the legacy installer to enable automated Ubuntu 20.04 _desktop_ installations, but this script is focused on the server version which has indeed moved to the Subiquity installer.

The problem you are seeing is due to changes that were made to the ISO image for Ubuntu 21.04, perhaps even earlier in 20.10. Again, as I explain in the README, this is only targeting Focal Fossa at the moment. Your issue has already been reported in #11 where I confirmed that I am working on expanding the compatibility of the script.

> produce a remastered ISO to auto-install 20.04 and later

Have you been able to use the script successfully for a 20.04 server ISO? If you are seeing issues with that I may be able to assist you.

**Comment by covertsh** [comment]
Closing since there has been no response.
