### ISSUE TITLE
temp files not removed

### ISSUE THREAD

**Issue by Hamsterman** [covertsh/ubuntu-autoinstall-generator#4]
I do this

bash ubuntu-autoinstall-generator.sh -a -u user-data

It completes fine but leaves the following files which should probably be removed

SHA256SUMS
SHA256SUMS.gpg
843938DF228D22F7B3742BC0D94AA3F0EFE21092.keyring

Also it seems if you leave those files and do the same command the day after it fails do to verification.

**Comment by covertsh** [comment]
Those files are kept intentionally so that they so can be reused and not downloaded over and over again when making multiple ISO images. I will need to modify the script to remove the SHA256SUMS files but keep the keyring file (which will not expire).

**Comment by covertsh** [comment]
Thanks for your bug report. I have instead added a date in the name of the SHA256SUMS files so that they are only downloaded for the current day if they do not already exist. I have also added a warning in the script output if a user tries to use the automatic GPG verification but does not use the current daily ISO image (because verification will fail).

I will not make the script remove those SHA256SUMS files at the end because they are useful for verifying a previously downloaded image again in the future. Also the keyring file does not expire on a daily basis so it can be reused for a long time (until the signing key is rotated).
