### ISSUE TITLE
Script stops when p7zip or mkisofs isn't installed

### ISSUE THREAD

**Issue by MBiesma** [covertsh/ubuntu-autoinstall-generator#8]
Not really an issue but maybe more of a way to make the script better..
I installed a fresh Ubuntu 20.04 and the following happens:

When p7zip is not installed, the script stops:

`[2021-04-30 16:07:45] 👶 Starting up...`
`[2021-04-30 16:07:45] 📁 Created temporary working directory /tmp/tmp.8SMZS8FBey`
`[2021-04-30 16:07:45] 🔎 Checking for required utilities...`
`[2021-04-30 16:07:45] 💥 7z is not installed.`
`[2021-04-30 16:07:45] 🚽 Deleted temporary working directory /tmp/tmp.8SMZS8FBey`

When mkisofs is not installed, the script stops:

`[2021-04-30 16:16:07] 👶 Starting up...`
`[2021-04-30 16:16:07] 📁 Created temporary working directory /tmp/tmp.iquBTfSerG`
`[2021-04-30 16:16:07] 🔎 Checking for required utilities...`
`[2021-04-30 16:16:07] 💥 mkisofs is not installed.`
`[2021-04-30 16:16:07] 🚽 Deleted temporary working directory /tmp/tmp.iquBTfSerG`

Maybe you can put in something like: if p7zip is not installed, then apt install p7zip -y
And something like: if p7zip is not installed, then apt install mkisofs -y

**Comment by covertsh** [comment]
Hi, thanks for your report.

As you know, the script requires those packages to be installed otherwise it will exit. The script can be run without root privileges (in fact, that is what I would suggest), which means that it would not have permission to install those packages anyway. On top of that, it already prints out a message indicating which package is missing so the user can install it. Perhaps instead of installing the packages automatically, we could improve the error message to ask the user to do it. What do you think about that possibility?

**Comment by ToddDTaft** [comment]
I encountered a similar issue with curl, although that probably depends upon what options are used when calling the program.  I think putting up a clear error message that says what command should be run to fix the issue is probably a good solution.  Even if the program were designed to be run as root, I don't think that installing system software without asking is a good thing.  You should probably have either a prompt or a separate command-line flag (e.g. -i = install necessary system software prerequisites) to do this.

**Comment by covertsh** [comment]
My concern with telling the user which package to install is that the package providing the ```7z``` command (for example) could be different on each Linux distribution. Although I only test on Ubuntu, the script can work on most distros. That's why the current behavior is to state which command is missing rather than the package name. Perhaps we could standardize on Ubuntu only and then add the package names to the error messages.

**Comment by covertsh** [comment]
I have improved the error message in the latest version of the script to include which packages need to be installed.

**Comment by MBiesma** [comment]
> My concern with telling the user which package to install is that the package providing the `7z` command (for example) could be different on each Linux distribution. Although I only test on Ubuntu, the script can work on most distros. That's why the current behavior is to state which command is missing rather than the package name. Perhaps we could standardize on Ubuntu only and then add the package names to the error messages.

I think you are right about that. To keep the script as universal as possible for lots of different distro’s. I like that you improved the error message in the latest version of the script to include which packages need to be installed. Keep up the good work! 👍🏻
